Repository novelrt/NovelRT, pull requests merged in 2019-12, with the labels that each got.

#73 UBO changes and variable aspect for adjustable FOV and viewport.
  CMakeLists.txt
  README.md
  src/BasicFragmentShader.glsl
  src/BasicVertexShader.glsl
  src/CameraBlock.h
  src/CameraViewChangedEventArgs.h
  src/FontFragmentShader.glsl
  src/FontVertexShader.glsl
  src/GeoBounds.cpp
  src/GeoBounds.h
  src/GeoMatrix4.h
  src/GeoVector.h
  src/GraphicsCharacterRenderData.h
  src/KeyCode.h
  src/Lazy.h
  src/NovelAudioService.cpp
  src/NovelAudioService.h
  src/NovelBasicFillRect.cpp
  src/NovelBasicFillRect.h
  src/NovelBasicInteractionRect.cpp
  src/NovelBasicInteractionRect.h
  src/NovelCamera.cpp
  src/NovelCamera.h
  src/NovelCommonArgs.h
  src/NovelDebugService.cpp
  src/NovelDebugService.h
  src/NovelImageRect.cpp
  src/NovelImageRect.h
  src/NovelInteractionObject.cpp
  src/NovelInteractionObject.h
  src/NovelInteractionService.cpp
  src/NovelInteractionService.h
  src/NovelLayeringService.cpp
  src/NovelLayeringService.h
  src/NovelObject.cpp
  src/NovelObject.h
  src/NovelObjectSortComparison.h
  src/NovelRTUtilities.h
  src/NovelRenderObject.cpp
  src/NovelRenderObject.h
  src/NovelRenderingService.cpp
  src/NovelRenderingService.h
  src/NovelRunner.cpp
  src/NovelRunner.h
  src/NovelRunner_C.cpp
  src/NovelRunner_C.h
  src/NovelStepTimer.cpp
  src/NovelStepTimer.h
  src/NovelTextRect.cpp
  src/NovelTextRect.h
  src/NovelWorldObject.cpp
  src/NovelWorldObject.h
  src/RGBAConfig.cpp
  src/RGBAConfig.h
  src/ShaderProgram.h
  src/TexturedFragmentShader.glsl
  src/TexturedVertexShader.glsl
  src/main.cpp
  src/wrapper.hpp
Labels: engine API, engine core, feature

#82 Implement spdlog and Logging Service
  CMakeLists.txt
  scripts/build.ps1
  scripts/build.sh
  src/NovelAudioService.cpp
  src/NovelAudioService.h
  src/NovelCamera.h
  src/NovelImageRect.cpp
  src/NovelImageRect.h
  src/NovelInteractionObject.h
  src/NovelInteractionService.h
  src/NovelLoggingService.cpp
  src/NovelLoggingService.h
  src/NovelRenderingService.cpp
  src/NovelRenderingService.h
  src/NovelTextRect.cpp
  src/NovelTextRect.h
  src/NovelUtilities.h
  src/main.cpp
  src/wrapper.hpp
Labels: engine API, engine core, feature

#92 [HOTFIX] Resolved struct export issue with NovelCommonArgs.
  src/NovelCommonArgs.h
Labels: bug, engine API, engine core

#93 feature: Add the option to dynamically set the window title
  src/NovelRenderingService.cpp
  src/NovelRenderingService.h
  src/NovelRunner.cpp
  src/NovelRunner.h
  src/main.cpp
Labels: engine API, engine core, feature

#97 Created centralised header file with all includes added
  CMakeLists.txt
  src/CameraBlock.h
  src/NovelRT.h
  src/main.cpp
Labels: engine API, engine core
