Repository novelrt/NovelRT, pull requests merged in 2019-08, with the labels that each got.

#16 Updating the code so MSVC builds succesfully
  CMakeLists.txt
  src/NovelBasicFillRect.cpp
  src/NovelInteractionObject.h
  src/NovelLayeringService.h
  src/main.cpp
Labels: engine core, no ticket

#17 Windows support.
  CMakeLists.txt
  src/NovelBasicFillRect.cpp
  src/NovelInteractionObject.h
  src/NovelLayeringService.h
  src/main.cpp
Labels: engine core, no ticket

#23 Baseline OpenGL pipeline
  .editorconfig
  CMakeLists.txt
  novel-chan.png
  src/BasicFragmentShader.glsl
  src/BasicVertexShader.glsl
  src/GeoBounds.cpp
  src/GeoBounds.h
  src/GeoVector.h
  src/NovelBasicFillRect.cpp
  src/NovelBasicFillRect.h
  src/NovelBasicInteractionRect.cpp
  src/NovelImageRect.cpp
  src/NovelImageRect.h
  src/NovelObject.cpp
  src/NovelObject.h
  src/NovelRenderObject.cpp
  src/NovelRenderObject.h
  src/NovelRenderingService.cpp
  src/NovelRenderingService.h
  src/RGBAConfig.cpp
  src/RGBAConfig.h
  src/TexturedFragmentShader.glsl
  src/TexturedVertexShader.glsl
  src/main.cpp
  test-yuri.png
Labels: engine API, engine core

#26 Updating GeoVector to wrap glm::vec<2, T>
  CMakeLists.txt
  src/GeoVector.h
Labels: engine core
