Repository novelrt/NovelRT, pull requests merged in 2020-12, with the labels that each got.

#237 ci: add github workflow config
  .github/workflows/continuous-integration.yml
Labels: CI/CD, windows

#243 Add a warning incase GCC is used.
  README.md
Labels: miscellaneous

#244 Updated codeowners file.
  CODEOWNERS
Labels: miscellaneous

#231 ECS framework (NovelRT::Ecs)
  include/NovelRT.h
  include/NovelRT/Atom.h
  include/NovelRT/Ecs/Catalogue.h
  include/NovelRT/Ecs/ComponentBuffer.h
  include/NovelRT/Ecs/ComponentCache.h
  include/NovelRT/Ecs/ComponentView.h
  include/NovelRT/Ecs/Ecs.h
  include/NovelRT/Ecs/EcsUtils.h
  include/NovelRT/Ecs/EntityCache.h
  include/NovelRT/Ecs/SparseSet.h
  include/NovelRT/Ecs/SystemScheduler.h
  include/NovelRT/Timing/StepTimer.h
  include/NovelRT/Timing/Timestamp.h
  include/NovelRT/Utilities/Event.h
  src/NovelRT/CMakeLists.txt
  src/NovelRT/Ecs/Catalogue.cpp
  src/NovelRT/Ecs/ComponentCache.cpp
  src/NovelRT/Ecs/EntityCache.cpp
  src/NovelRT/Ecs/SystemScheduler.cpp
  tests/NovelRT.Tests/CMakeLists.txt
  tests/NovelRT.Tests/Ecs/CatalogueTest.cpp
  tests/NovelRT.Tests/Ecs/ComponentBufferTest.cpp
  tests/NovelRT.Tests/Ecs/ComponentCacheTest.cpp
  tests/NovelRT.Tests/Ecs/ComponentViewTest.cpp
  tests/NovelRT.Tests/Ecs/EntityCacheTest.cpp
  tests/NovelRT.Tests/Ecs/SparseSetTest.cpp
  tests/NovelRT.Tests/Ecs/SystemSchedulerTest.cpp
Labels: engine api, engine core, feature
