Repository novelrt/NovelRT, pull requests merged in 2020-07, with the labels that each got.

#201 API mish-mash fix.
  include/NovelRT/Graphics/Camera.h
  include/NovelRT/Graphics/TextRect.h
Labels: bug, engine api

#199 Transparency and Background Colour changing support
  include/NovelRT/Graphics/RenderingService.h
  include/NovelRT/NovelRunner.h
  include/NovelRT/Windowing/WindowingService.h
  src/NovelRT/Graphics/RenderingService.cpp
  src/NovelRT/NovelRunner.cpp
  src/NovelRT/Windowing/WindowingService.cpp
Labels: engine api, engine core, feature

#202 Updated samples and novel-chan.
  samples/main.cpp
  src/Resources/Images/novel-chan.png
Labels: miscellaneous

#196 Refactor CI environment and build system
  CMakeLists.txt
  LICENCE.md
  README.md
  cmake/FindDotnet.cmake
  cmake/FindGLFW.cmake
  cmake/FindGMock.cmake
  cmake/FindGTest.cmake
  cmake/FindSndfile.cmake
  cmake/Findglad.cmake
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  include/NovelRT.h
  include/NovelRT/DotNet/RuntimeService.h
  include/NovelRT/DotNet/coreclr_delegates.h
  include/NovelRT/DotNet/hostfxr.h
  resources/CMakeLists.txt
  resources/Fonts/Gayathri-Regular.ttf
  resources/Fonts/Raleway-Regular.ttf
  resources/Images/novel-chan.png
  resources/Scripts/avg.lua
  resources/Shaders/BasicFragmentShader.glsl
  resources/Shaders/BasicVertexShader.glsl
  resources/Shaders/FontFragmentShader.glsl
  resources/Shaders/FontVertexShader.glsl
  resources/Shaders/TexturedFragmentShader.glsl
  resources/Shaders/TexturedVertexShader.glsl
  samples/CMakeLists.txt
  samples/Simple/CMakeLists.txt
  samples/Simple/main.cpp
  scripts/azure-pipelines.yml
  scripts/azure-unix.yml
  scripts/azure-windows.yml
  scripts/build.ps1
  scripts/build.sh
  scripts/machine-setup.cmd
  scripts/machine-setup.ps1
  scripts/machine-setup.sh
  scripts/novelrt-build.linux.Dockerfile
  src/CMakeLists.txt
  src/Config.cmake.in
  src/NovelRT.DotNet/CMakeLists.txt
  src/NovelRT.DotNet/NovelRT.DotNet.csproj
  src/NovelRT.DotNet/test.cs
  src/NovelRT/CMakeLists.txt
  src/NovelRT/DotNet/RuntimeService.cpp
  tests/CMakeLists.txt
  tests/NovelRT.Tests/CMakeLists.txt
  tests/NovelRT.Tests/main.cpp
Labels: cmake, linux: ubuntu, windows

#205 System decoupling and refactor.
  include/NovelRT/Audio/AudioService.h
  include/NovelRT/DebugService.h
  include/NovelRT/DotNet/RuntimeService.h
  include/NovelRT/Graphics/FontSet.h
  include/NovelRT/Graphics/RenderingService.h
  include/NovelRT/Graphics/Texture.h
  include/NovelRT/Input/InteractionService.h
  include/NovelRT/NovelRunner.h
  include/NovelRT/Windowing/WindowingService.h
  samples/Simple/main.cpp
  src/NovelRT/Audio/AudioService.cpp
  src/NovelRT/DebugService.cpp
  src/NovelRT/DotNet/RuntimeService.cpp
  src/NovelRT/Graphics/FontSet.cpp
  src/NovelRT/Graphics/RenderingService.cpp
  src/NovelRT/Graphics/Texture.cpp
  src/NovelRT/Input/InteractionService.cpp
  src/NovelRT/NovelRunner.cpp
  src/NovelRT/Windowing/WindowingService.cpp
Labels: engine api, engine core

#210 [SUPER HACKY HOTFIX] This should fix nethost for the samples for now.
  samples/Simple/CMakeLists.txt
Labels: bug, cmake, windows

#211 Minor README update.
  README.md
Labels: miscellaneous

#212 Ported the Engine target to a shared library.
  CMakeLists.txt
  cmake/Findglad.cmake
  samples/Simple/CMakeLists.txt
  src/NovelRT/CMakeLists.txt
  tests/NovelRT.Tests/CMakeLists.txt
Labels: cmake, linux: ubuntu, windows

#207 Fix all broken logging statements.
  include/NovelRT/DotNet/RuntimeService.h
  samples/Simple/main.cpp
  src/NovelRT/Audio/AudioService.cpp
  src/NovelRT/DotNet/RuntimeService.cpp
  src/NovelRT/Graphics/FontSet.cpp
  src/NovelRT/Graphics/RenderingService.cpp
  src/NovelRT/Graphics/Texture.cpp
  src/NovelRT/NovelRunner.cpp
  src/NovelRT/Windowing/WindowingService.cpp
Labels: bug, engine core
