Repository novelrt/NovelRT, pull requests merged in 2020-02, with the labels that each got.

#141 Forward variadic arguments instead of adding on new line
  include/NovelRT/LoggingService.h
Labels: bug, engine core

#136 Fixed zero-tick delta behavior (#41)
  src/NovelRT/Timing/StepTimer.cpp
Labels: engine core

#122 Add helper method for throwing on nullptrs and apply where necessary
  include/NovelRT/LoggingService.h
  samples/main.cpp
  src/NovelRT/Graphics/ImageRect.cpp
  src/NovelRT/LoggingService.cpp
  src/NovelRT/Windowing/WindowingService.cpp
Labels: engine api, engine core, miscellaneous

#135 Basic animation toolset and structural changes.
  include/NovelRT.h
  include/NovelRT/Animation/AnimatorPlayState.h
  include/NovelRT/Animation/SpriteAnimator.h
  include/NovelRT/Animation/SpriteAnimatorFrame.h
  include/NovelRT/Animation/SpriteAnimatorState.h
  include/NovelRT/Atom.h
  include/NovelRT/Graphics/FontSet.h
  include/NovelRT/Graphics/GraphicsCharacterRenderData.h
  include/NovelRT/Graphics/ImageRect.h
  include/NovelRT/Graphics/RenderingService.h
  include/NovelRT/Graphics/TextRect.h
  include/NovelRT/Graphics/Texture.h
  include/NovelRT/NovelRunner.h
  include/NovelRT/Utilities/Event.h
  include/NovelRT/Utilities/Lazy.h
  samples/main.cpp
  src/NovelRT/Animation/SpriteAnimator.cpp
  src/NovelRT/DebugService.cpp
  src/NovelRT/Graphics/FontSet.cpp
  src/NovelRT/Graphics/ImageRect.cpp
  src/NovelRT/Graphics/RenderingService.cpp
  src/NovelRT/Graphics/TextRect.cpp
  src/NovelRT/Graphics/Texture.cpp
  src/NovelRT/NovelRunner.cpp
  src/NovelRT/Windowing/WindowingService.cpp
  tests/NovelRT.Tests/Animation/SpriteAnimatorStateTest.cpp
  tests/NovelRT.Tests/Maths/QuadTreeTest.cpp
  tests/NovelRT.Tests/Utilities/EventTest.cpp
  tests/NovelRT.Tests/main.cpp
Labels: engine api, engine core, feature

#145 Added detection for NVIDIA Optimus (Win x86/x64 only)
  include/NovelRT/Windowing/WindowingService.h
  src/NovelRT/Windowing/WindowingService.cpp
Labels: engine core, feature, windows
