Repository novelrt/NovelRT, pull requests merged in 2021-05, with the labels that each got.

#298 Fixed missing return code.
  src/NovelRT.Interop/Ecs/NrtCatalogue.cpp
  tests/NovelRT.Tests/Interop/Ecs/NrtCatalogueTest.cpp
Labels: bug, engine api

#306 Nullptr return code parity
  include/NovelRT.Interop/Graphics/NrtBasicFillRect.h
  include/NovelRT.Interop/Graphics/NrtTextRect.h
  include/NovelRT.Interop/Input/NrtBasicInteractionRect.h
  include/NovelRT.Interop/NrtTypedefs.h
  src/NovelRT.DotNet/Interop/Core/NrtResult.cs
  src/NovelRT.Interop/Animation/NrtSpriteAnimator.cpp
  src/NovelRT.Interop/Animation/NrtSpriteAnimatorFrame.cpp
  src/NovelRT.Interop/Animation/NrtSpriteAnimatorState.cpp
  src/NovelRT.Interop/Audio/NrtAudioService.cpp
  src/NovelRT.Interop/DotNet/NrtRuntimeService.cpp
  src/NovelRT.Interop/Ecs/NrtCatalogue.cpp
  src/NovelRT.Interop/Ecs/NrtComponentBufferMemoryContainer.cpp
  src/NovelRT.Interop/Ecs/NrtComponentCache.cpp
  src/NovelRT.Interop/Ecs/NrtEntityCache.cpp
  src/NovelRT.Interop/Ecs/NrtEntityIdVector.cpp
  src/NovelRT.Interop/Ecs/NrtSparseSetMemoryContainer.cpp
  src/NovelRT.Interop/Ecs/NrtSystemScheduler.cpp
  src/NovelRT.Interop/Ecs/NrtUnsafeComponentView.cpp
  src/NovelRT.Interop/Graphics/NrtBasicFillRect.cpp
  src/NovelRT.Interop/Graphics/NrtCamera.cpp
  src/NovelRT.Interop/Graphics/NrtFontSet.cpp
  src/NovelRT.Interop/Graphics/NrtImageRect.cpp
  src/NovelRT.Interop/Graphics/NrtRGBAConfig.cpp
  src/NovelRT.Interop/Graphics/NrtRenderingService.cpp
  src/NovelRT.Interop/Graphics/NrtTextRect.cpp
  src/NovelRT.Interop/Graphics/NrtTexture.cpp
  src/NovelRT.Interop/Ink/NrtInkService.cpp
  src/NovelRT.Interop/Input/NrtBasicInteractionRect.cpp
  src/NovelRT.Interop/Input/NrtInteractionService.cpp
  src/NovelRT.Interop/Maths/NrtGeoBounds.cpp
  src/NovelRT.Interop/Maths/NrtQuadTree.cpp
  src/NovelRT.Interop/Maths/NrtQuadTreePoint.cpp
  src/NovelRT.Interop/NrtDebugService.cpp
  src/NovelRT.Interop/NrtLoggingService.cpp
  src/NovelRT.Interop/NrtNovelRunner.cpp
  src/NovelRT.Interop/SceneGraph/NrtQuadTreeNode.cpp
  src/NovelRT.Interop/SceneGraph/NrtQuadTreeScenePoint.cpp
  src/NovelRT.Interop/SceneGraph/NrtRenderObjectNode.cpp
  src/NovelRT.Interop/SceneGraph/NrtScene.cpp
  src/NovelRT.Interop/SceneGraph/NrtSceneNode.cpp
  src/NovelRT.Interop/SceneGraph/NrtSceneNodeBreadthFirstIterator.cpp
  src/NovelRT.Interop/SceneGraph/NrtSceneNodeDepthFirstIterator.cpp
  src/NovelRT.Interop/Timing/NrtStepTimer.cpp
  src/NovelRT.Interop/Windowing/NrtWindowingService.cpp
  tests/NovelRT.Tests/Interop/Maths/GeoBoundsTest.cpp
  tests/NovelRT.Tests/Interop/Maths/QuadTreePointTest.cpp
  tests/NovelRT.Tests/Interop/Maths/QuadTreeTest.cpp
Labels: engine api, feature

#311 Bugfix/system scheduler logic error and added unit test
  include/NovelRT.Interop/Ecs/NrtEcsTypedefs.h
  include/NovelRT/Ecs/ComponentBuffer.h
  include/NovelRT/Ecs/ComponentBufferMemoryContainer.h
  include/NovelRT/Ecs/ComponentCache.h
  include/NovelRT/Ecs/SystemScheduler.h
  src/NovelRT.Interop/Ecs/NrtComponentBufferMemoryContainer.cpp
  src/NovelRT/Ecs/ComponentBufferMemoryContainer.cpp
  src/NovelRT/Ecs/ComponentCache.cpp
  src/NovelRT/Ecs/SystemScheduler.cpp
  tests/NovelRT.Tests/Ecs/ComponentBufferMemoryContainerTest.cpp
  tests/NovelRT.Tests/Ecs/SystemSchedulerTest.cpp
  tests/NovelRT.Tests/Interop/Ecs/NrtCatalogueTest.cpp
  tests/NovelRT.Tests/Interop/Ecs/NrtComponentBufferMemoryContainerTest.cpp
  tests/NovelRT.Tests/Interop/Ecs/NrtSystemSchedulerTest.cpp
Labels: bug, engine api, engine core
