Repository novelrt/NovelRT, pull requests merged in 2022-06, with the labels that each got.

#441 Add Fabulist integration.
  CMakeLists.txt
  include/NovelRT/NovelRT.h
  internal/CMakeLists.txt
  internal/Fabulist/CMakeLists.txt
  samples/CMakeLists.txt
  samples/FabulistTest/CMakeLists.txt
  samples/FabulistTest/main.cpp
  src/NovelRT/CMakeLists.txt
Labels: feature, engine core, blocked

#451 Move GLFW to a FetchContent dependency.
  CMakeLists.txt
  conanfile.py
  internal/CMakeLists.txt
  internal/glfw/CMakeLists.txt
  src/NovelRT/CMakeLists.txt
Labels: cmake

#452 Move spdlog to a FetchContent dependency.
  CMakeLists.txt
  conanfile.py
  internal/CMakeLists.txt
  internal/spdlog/CMakeLists.txt
  src/NovelRT/CMakeLists.txt
Labels: cmake

#459 Static link from-source build of libpng via FetchContent.
  .gitignore
  conanfile.py
  internal/CMakeLists.txt
  internal/libpng/CMakeLists.txt
  src/NovelRT/CMakeLists.txt
Labels: cmake

#461 Fixed MacOs Glfw SigAbort when creating a window
  src/NovelRT/Windowing/Glfw/GlfwWindowingDevice.cpp
Labels: bug, engine core, mac

#463 Fix buffer overflow caused by underflowing size_t object.
  src/NovelRT/Ecs/SparseSetMemoryContainer.cpp
Labels: bug, engine core

#465 Fix FutureResult race condition with the GPU.
  src/NovelRT/Ecs/Graphics/DefaultRenderingSystem.cpp
Labels: bug, engine core
