Repository novelrt/NovelRT, pull requests merged in 2022-10, with the labels that each got.

#505 Fix broken test that validated duplicate values upon binpackage load.
  tests/NovelRT.Tests/Persistence/ChapterTest.cpp
Labels: bug

#508 Fix badge on README
  README.md
Labels: hacktoberfest-accepted

#510 Changed cmake var used for builds
  CMakeLists.txt
  doxygen/CMakeLists.txt
  resources/CMakeLists.txt
  src/NovelRT.Interop/CMakeLists.txt
  src/NovelRT/CMakeLists.txt
  tests/NovelRT.Tests/CMakeLists.txt
Labels: hacktoberfest-accepted

#518 Add minimal support for `ResourceManagement` namespace in the C API.
  include/NovelRT.Interop/NrtErrorHandling.h
  include/NovelRT.Interop/NrtTypedefs.h
  include/NovelRT.Interop/ResourceManagement/NrtBinaryMemberMetadata.h
  include/NovelRT.Interop/ResourceManagement/NrtBinaryPackage.h
  include/NovelRT.Interop/ResourceManagement/NrtFilePathUuidMap.h
  include/NovelRT.Interop/ResourceManagement/NrtResourceLoader.h
  include/NovelRT.Interop/ResourceManagement/NrtResourceManagement.h
  include/NovelRT.Interop/ResourceManagement/NrtResourceManagementTypedefs.h
  include/NovelRT.Interop/ResourceManagement/NrtShaderMetadata.h
  include/NovelRT.Interop/ResourceManagement/NrtTextureMetadata.h
  include/NovelRT.Interop/ResourceManagement/NrtUint8Vector.h
  include/NovelRT.Interop/ResourceManagement/NrtUuidFilePathMap.h
  include/NovelRT/NovelRT.h
  include/NovelRT/ResourceManagement/BinaryDataType.h
  include/NovelRT/ResourceManagement/BinaryMemberMetadata.h
  include/NovelRT/ResourceManagement/BinaryPackage.h
  include/NovelRT/ResourceManagement/ShaderMetadata.h
  src/NovelRT.Interop/Audio/NrtAudioService.cpp
  src/NovelRT.Interop/CMakeLists.txt
  src/NovelRT.Interop/Ecs/Audio/NrtAudioSystem.cpp
  src/NovelRT.Interop/Ecs/Graphics/NrtDefaultRenderingSystem.cpp
  src/NovelRT.Interop/Ecs/NrtCatalogue.cpp
  src/NovelRT.Interop/Ecs/NrtComponentBufferMemoryContainer.cpp
  src/NovelRT.Interop/Ecs/NrtComponentCache.cpp
  src/NovelRT.Interop/Ecs/NrtEntityCache.cpp
  src/NovelRT.Interop/Ecs/NrtEntityIdVector.cpp
  src/NovelRT.Interop/Ecs/NrtSparseSetMemoryContainer.cpp
  src/NovelRT.Interop/Ecs/NrtSystemScheduler.cpp
  src/NovelRT.Interop/Ecs/NrtUnsafeComponentView.cpp
  src/NovelRT.Interop/Maths/NrtGeoBounds.cpp
  src/NovelRT.Interop/Maths/NrtQuadTree.cpp
  src/NovelRT.Interop/Maths/NrtQuadTreePoint.cpp
  src/NovelRT.Interop/NrtInteropErrorHandling.cpp
  src/NovelRT.Interop/NrtLoggingService.cpp
  src/NovelRT.Interop/ResourceManagement/NrtBinaryMemberMetadata.cpp
  src/NovelRT.Interop/ResourceManagement/NrtBinaryPackage.cpp
  src/NovelRT.Interop/ResourceManagement/NrtFilePathUuidMap.cpp
  src/NovelRT.Interop/ResourceManagement/NrtResourceLoader.cpp
  src/NovelRT.Interop/ResourceManagement/NrtShaderMetadata.cpp
  src/NovelRT.Interop/ResourceManagement/NrtTextureMetadata.cpp
  src/NovelRT.Interop/ResourceManagement/NrtUint8Vector.cpp
  src/NovelRT.Interop/ResourceManagement/NrtUuidFilePathMap.cpp
  src/NovelRT.Interop/SceneGraph/NrtQuadTreeNode.cpp
  src/NovelRT.Interop/SceneGraph/NrtQuadTreeScenePoint.cpp
  src/NovelRT.Interop/SceneGraph/NrtScene.cpp
  src/NovelRT.Interop/SceneGraph/NrtSceneNode.cpp
  src/NovelRT.Interop/SceneGraph/NrtSceneNodeBreadthFirstIterator.cpp
  src/NovelRT.Interop/SceneGraph/NrtSceneNodeDepthFirstIterator.cpp
  src/NovelRT.Interop/Timing/NrtStepTimer.cpp
  src/NovelRT.Interop/Utilities/NrtMisc.cpp
  tests/NovelRT.Tests/CMakeLists.txt
  tests/NovelRT.Tests/Interop/ResourceManagement/BinaryMemberMetadataTest.cpp
Labels: feature, engine api

#499 Add resource loading support for audio files.
  include/NovelRT.Interop/Audio/NrtAudioService.h
  include/NovelRT.Interop/NrtTypedefs.h
  include/NovelRT.Interop/ResourceManagement/NrtAudioMetadata.h
  include/NovelRT.Interop/ResourceManagement/NrtInt16Vector.h
  include/NovelRT.Interop/ResourceManagement/NrtResourceManagement.h
  include/NovelRT.Interop/ResourceManagement/NrtResourceManagementTypedefs.h
  include/NovelRT/Audio/AudioService.h
  include/NovelRT/Ecs/Audio/AudioSystem.h
  include/NovelRT/Ecs/Configurator.h
  include/NovelRT/PluginManagement/IGraphicsPluginProvider.h
  include/NovelRT/PluginManagement/IInputPluginProvider.h
  include/NovelRT/PluginManagement/IResourceManagementPluginProvider.h
  include/NovelRT/PluginManagement/IWindowingPluginProvider.h
  include/NovelRT/ResourceManagement/AudioMetadata.h
  include/NovelRT/ResourceManagement/Desktop/DesktopResourceLoader.h
  include/NovelRT/ResourceManagement/Desktop/ResourceManagement.Desktop.h
  include/NovelRT/ResourceManagement/ResourceLoader.h
  include/NovelRT/ResourceManagement/ResourceManagement.h
  samples/AudioEcsSample/main.cpp
  src/NovelRT.Interop/Audio/NrtAudioService.cpp
  src/NovelRT.Interop/CMakeLists.txt
  src/NovelRT.Interop/Ecs/Audio/NrtAudioSystem.cpp
  src/NovelRT.Interop/ResourceManagement/NrtAudioMetadata.cpp
  src/NovelRT.Interop/ResourceManagement/NrtInt16Vector.cpp
  src/NovelRT/Audio/AudioService.cpp
  src/NovelRT/Ecs/Audio/AudioSystem.cpp
  src/NovelRT/ResourceManagement/Desktop/DesktopResourceLoader.cpp
Labels: feature, engine core, engine api
